//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int orderid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> userid { get; set; }
        public string acceptname { get; set; }
        public string address { get; set; }
        public string postalcode { get; set; }
        public string phone { get; set; }
        public string delivery { get; set; }
        public string payment { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> ordertime { get; set; }
        public Nullable<int> orderprice { get; set; }
    }
}
